customNonSolidMaterials:
- ACACIA_DOOR
- ACACIA_FENCE_GATE
- ACACIA_PRESSURE_PLATE
- ACACIA_SIGN
- ACACIA_TRAPDOOR
- ACACIA_WALL_SIGN
- BIRCH_DOOR
- BIRCH_FENCE_GATE
- BIRCH_PRESSURE_PLATE
- BIRCH_SIGN
- BIRCH_TRAPDOOR
- BIRCH_WALL_SIGN
- BLACK_BANNER
- BLACK_WALL_BANNER
- BLUE_BANNER
- BLUE_WALL_BANNER
- BROWN_BANNER
- BROWN_WALL_BANNER
- CRIMSON_DOOR
- CRIMSON_FENCE_GATE
- CRIMSON_PRESSURE_PLATE
- CRIMSON_SIGN
- CRIMSON_TRAPDOOR
- CRIMSON_WALL_SIGN
- CYAN_BANNER
- CYAN_WALL_BANNER
- DARK_OAK_DOOR
- DARK_OAK_FENCE_GATE
- DARK_OAK_PRESSURE_PLATE
- DARK_OAK_SIGN
- DARK_OAK_TRAPDOOR
- DARK_OAK_WALL_SIGN
- DEAD_BRAIN_CORAL
- DEAD_BRAIN_CORAL_FAN
- DEAD_BRAIN_CORAL_WALL_FAN
- DEAD_BUBBLE_CORAL
- DEAD_BUBBLE_CORAL_FAN
- DEAD_BUBBLE_CORAL_WALL_FAN
- DEAD_FIRE_CORAL
- DEAD_FIRE_CORAL_FAN
- DEAD_FIRE_CORAL_WALL_FAN
- DEAD_HORN_CORAL
- DEAD_HORN_CORAL_FAN
- DEAD_HORN_CORAL_WALL_FAN
- DEAD_TUBE_CORAL
- DEAD_TUBE_CORAL_FAN
- DEAD_TUBE_CORAL_WALL_FAN
- GRAY_BANNER
- GRAY_WALL_BANNER
- GREEN_BANNER
- GREEN_WALL_BANNER
- HEAVY_WEIGHTED_PRESSURE_PLATE
- IRON_DOOR
- IRON_TRAPDOOR
- JUKEBOX
- JUNGLE_DOOR
- JUNGLE_FENCE_GATE
- JUNGLE_PRESSURE_PLATE
- JUNGLE_SIGN
- JUNGLE_TRAPDOOR
- JUNGLE_WALL_SIGN
- LIGHT_BLUE_BANNER
- LIGHT_BLUE_WALL_BANNER
- LIGHT_GRAY_BANNER
- LIGHT_GRAY_WALL_BANNER
- LIGHT_WEIGHTED_PRESSURE_PLATE
- LIME_BANNER
- LIME_WALL_BANNER
- MAGENTA_BANNER
- MAGENTA_WALL_BANNER
- OAK_DOOR
- OAK_FENCE_GATE
- OAK_PRESSURE_PLATE
- OAK_SIGN
- OAK_TRAPDOOR
- OAK_WALL_SIGN
- ORANGE_BANNER
- ORANGE_WALL_BANNER
- PINK_BANNER
- PINK_WALL_BANNER
- POLISHED_BLACKSTONE_PRESSURE_PLATE
- PURPLE_BANNER
- PURPLE_WALL_BANNER
- RED_BANNER
- RED_WALL_BANNER
- SPRUCE_DOOR
- SPRUCE_FENCE_GATE
- SPRUCE_PRESSURE_PLATE
- SPRUCE_SIGN
- SPRUCE_TRAPDOOR
- SPRUCE_WALL_SIGN
- STONE_PRESSURE_PLATE
- WARPED_DOOR
- WARPED_FENCE_GATE
- WARPED_PRESSURE_PLATE
- WARPED_SIGN
- WARPED_TRAPDOOR
- WARPED_WALL_SIGN
- WHITE_BANNER
- WHITE_WALL_BANNER
- YELLOW_BANNER
- YELLOW_WALL_BANNER
- MANGROVE_PROPAGULE
- MANGROVE_DOOR
- MANGROVE_FENCE_GATE
- MANGROVE_PRESSURE_PLATE
- MANGROVE_SIGN
- MANGROVE_TRAPDOOR
- MANGROVE_WALL_SIGN
